"""added date_created/date_last_modified

Revision ID: ac8aeb34396b
Revises: 
Create Date: 2024-05-13 14:49:03.025496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac8aeb34396b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drug_screening_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('date_last_modified', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('family_and_supports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('date_last_modified', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('infant_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('date_last_modified', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('maternal_demographics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('date_last_modified', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('maternal_medical_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('date_last_modified', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('medical_services_for_substance_use', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('date_last_modified', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('psychiatric_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('date_last_modified', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('referrals_and_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('date_last_modified', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('relapse_prevention_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('date_last_modified', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('substance_use_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('date_last_modified', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('date_created')

    with op.batch_alter_table('substance_use_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_last_modified')
        batch_op.drop_column('date_created')

    with op.batch_alter_table('relapse_prevention_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_last_modified')
        batch_op.drop_column('date_created')

    with op.batch_alter_table('referrals_and_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_last_modified')
        batch_op.drop_column('date_created')

    with op.batch_alter_table('psychiatric_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_last_modified')
        batch_op.drop_column('date_created')

    with op.batch_alter_table('medical_services_for_substance_use', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_last_modified')
        batch_op.drop_column('date_created')

    with op.batch_alter_table('maternal_medical_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_last_modified')
        batch_op.drop_column('date_created')

    with op.batch_alter_table('maternal_demographics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_last_modified')
        batch_op.drop_column('date_created')

    with op.batch_alter_table('infant_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_last_modified')
        batch_op.drop_column('date_created')

    with op.batch_alter_table('family_and_supports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_last_modified')
        batch_op.drop_column('date_created')

    with op.batch_alter_table('drug_screening_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_last_modified')
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
